### ISSUE TITLE
Volume inexistent for Bitcoin

### ISSUE THREAD

**Issue by PrinceMatthew** [tixlfinance/tixlfinance-community-data#110]
**Describe the bug**

Coins with less volume appear on the Tixl Score graph with a higher score than even Bitcoin.

**To Reproduce**
 
1. Go to any coin with less volume (e.g. Yearn.finance)
2. Scroll down to Tixl Score graph
4. See the obvious difference

**Expected behavior**

Bitcoin should have a higher score on the Volume side because it has higher volume on multiple exchanges.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Browser Firefox
 - Version 84

**Smartphone (please complete the following information):**
 - Device: Samsung S9
 - OS: Android 10
 - Browser Firefox
 - Version 84

 **Screenshots**
![bitcoin](https://user-images.githubusercontent.com/37705192/104289071-58ca3400-54c1-11eb-80df-33cb23d7deb7.png)
![yearn](https://user-images.githubusercontent.com/37705192/104289087-5d8ee800-54c1-11eb-87ab-074ff05dd68e.png)

**Comment by fnnhnsn** [comment]
Hey Matthew, thanks a lot for the bug report! We're on to that as well and that is one topic we will have to deal with before we can progress from the beta state to a stable version (v1).

**Comment by PrinceMatthew** [comment]
Marking this as closed, because bug has been resolved.

**Comment by PrinceMatthew** [comment]
Bitcoin still experiencing this bug.

**Comment by PrinceMatthew** [comment]
![btcvseth](https://user-images.githubusercontent.com/37705192/106256039-76b6c900-6223-11eb-87c6-65b34fe37a61.png)

**Comment by fnnhnsn** [comment]
Hey Matthew, thanks a lot, we solved the issue!
