### ISSUE TITLE
Volume Graph empty on Nano page

### ISSUE THREAD

**Issue by catablogger** [tixlfinance/tixlfinance-community-data#182]
**Describe the bug**

The Volume graph under 'Price & Market Cap' on https://tixl.finance/projects/Nano is empty

**To Reproduce**

1. Go to 'https://tixl.finance/projects/Nano'
2. Scroll down to 'Price & Market Cap'
3. See problem on 1Y Volume graph

**Expected behavior**

Volume graph should have content

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Brave
 - Version 1.20.108
![CaptureNano](https://user-images.githubusercontent.com/79124861/108969567-b5259380-76bc-11eb-90c1-6aacb99c2910.PNG)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by fnnhnsn** [comment]
Hey @catablogger thanks a lot for your feedback, we managed to update the project.
